# Generated by Django 5.1.7 on 2025-03-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_user_id', models.CharField(max_length=255)),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('track_popularity', models.IntegerField()),
                ('track_url', models.URLField()),
                ('time_range', models.CharField(choices=[('short_term', 'Short Term'), ('medium_term', 'Medium Term'), ('long_term', 'Long Term')], max_length=50)),
                ('artist_genres', models.TextField(blank=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
